### ISSUE TITLE
Ability to specify server?

### ISSUE THREAD

**Issue by ohmantics** [LeonStraathof/pfsense-speedtest-widget#1]
Ookla speedtest is often confused about my location due to some unknown artifact of how Comcast Business routes my traffic. (e.g. I'm in San Francisco and right now it thinks I'm way over in Fairfield.)

It would be great if there were a feature to be able to specify favorite servers to test against.

**Comment by LeonStraathof** [comment]
This actually a good addition. I will look into the possibilities.

**Comment by reddit-reaper** [comment]
sorry for offtopic, didn't want to make another issue for this, just wanted to say TY for this widget its great and very useful :)

**Comment by tomatoinaction** [comment]
**you can specify it manually by changing in /usr/local/www/widgets/widgets/speedtest.widget.php**
speedtest --accept-license --accept-gdpr
to e.g. speedtest --server-id=16415 --accept-license --accept-gdpr

i had to do it bc my isp has its own server and there i shapes the upload^^

**but i also think a dropdown menu of the output from** 
speedtest -L 
in the widget would be nice - if possible


**for me it would be nice if you could parse the "packet-loss" output into the widget**


thanks for your great work btw! @LeonStraathof
